[package]
name = "ratatui-ext"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Extensions for ratatui"
keywords = ["tui", "terminal", "dashboard"]

[dependencies]
crossterm = "0.29"
ratatui = "0.29"
